workflows:
  flutter-android:
    name: Flutter Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: true
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
