workflows:
  flutter-android:
    name: Flutter Android AAB Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: true
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Patch isar_flutter_libs to support AGP 8+
        script: |
          echo "Patching isar_flutter_libs build.gradle to add namespace..."
          PLUGIN_DIR="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android"
          if [ -f "$PLUGIN_DIR/build.gradle" ]; then
            sed -i '/^android {/a \    namespace "com.isar.flutter.libs"' "$PLUGIN_DIR/build.gradle"
            echo "Patch applied. Showing updated build.gradle:"
            cat "$PLUGIN_DIR/build.gradle"
          else
            echo "isar_flutter_libs not found — skipping patch"
          fi

      - name: Build AAB
        script: flutter build appbundle --debug

    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab
