workflows:
  flutter-android:
    name: Flutter Android AAB Build
    max_build_duration: 60
    environment:
      flutter: stable
      android: true
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Patch isar_flutter_libs build.gradle with namespace
        script: |
          echo "Patching isar_flutter_libs..."
          ISAR_DIR="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android"
          FILE="$ISAR_DIR/build.gradle"
          if grep -q 'namespace' "$FILE"; then
            echo "Namespace already set, skipping patch."
          else
            sed -i '/^android {/a \    namespace "com.isar.flutter.libs"' "$FILE"
            echo "Namespace inserted into isar_flutter_libs build.gradle"
          fi

      - name: Build Android App Bundle
        script: flutter build appbundle --debug

    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab
