workflows:
  flutter-build:
    name: Build Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.myapp" # change to your actual app ID
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
